# Generated by Django 3.2.11 on 2022-11-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('messgae_text', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('is_reply', models.BooleanField(default=False)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_support.message')),
            ],
        ),
    ]
