# Generated by Django 3.2.11 on 2022-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0002_rename_messgae_text_message_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_be_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(max_length=1000),
        ),
    ]
