# Generated by Django 3.2.11 on 2022-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0003_auto_20221126_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
