# Generated by Django 3.2.11 on 2022-11-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0004_message_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_reply',
        ),
    ]
